config/routes.rb
Rails.application.routes.draw do

  root 'search#overview', as: 'search_overview'

  get 'analysis_projects/:id' => 'analysis_projects#overview', as: 'analysis_project_overview'
  get 'analysis_projects/:id/timeline' => 'timelines#analysis_project', as: 'analysis_project_timeline'
  get 'analysis_projects/:id/failed_instrument_data' => 'analysis_projects#failed_instrument_data', as: 'analysis_project_failed_instrument_data'
  get 'models/:id' => 'models#status', as: 'model_status'
  get 'models' => 'models#overview', as: 'model_overview'
  get 'model_groups/coverage/:id' => 'model_groups#coverage', as: 'model_group_coverage'
  get 'model_groups/:id' => 'model_groups#overview', as: 'model_group_overview'
  get 'builds/:id' => 'builds#status', as: 'build_status'
  get 'processing_profiles/:id' => 'processing_profiles#overview', as: 'processing_profile_overview'
  get 'disks' => 'disks#overview', as: 'disk_overview'
  get 'software_results/:id' => 'software_results#overview', as: 'software_result_overview'
  get 'subjects/:id' => 'subjects#overview', as: 'subject_overview'
  get 'libraries/:id' => 'libraries#overview', as: 'library_overview'
  get '/search' => 'search#results', as: 'search_results'

end

app/models/library.rb
class Library < ActiveRecord::Base
  self.table_name = 'instrument.fragment_library'
  self.primary_key = 'library_id'

  has_many :instrument_data, inverse_of: :library

  belongs_to :sample, class_name: 'Subject', inverse_of: :libraries
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def overview
    @library = Library.where(:library_id => params[:id]).first!
    @sample = @library.sample
  end
end

app/views/libraries/overview.html.haml
.row
  .container-fluid
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          = @library.full_name
    .row
      .col-md-10.col-md-offset-1
        %h4 Library Information
        .well
          .col-md-6
            %dl.dl-horizontal
              %dt Sample:
              %dd= link_to @sample.name, subject_overview_path(id: @sample.subject_id)
              %dt Library Insert Size:
              %dd= @library.library_insert_size
              %dt Original Insert Size:
              %dd= @library.original_insert_size
          .col-md-6
            %dl.dl-horizontal
              %dt Protocol:
              %dd= @library.protocol
              %dt Transcript Strand:
              %dd= @library.transcript_strand
              %dt Bisulfite Conversion:
              %dd= @library.bisulfite_conversion
          .clearfix