config/routes.rb
Rails.application.routes.draw do

  root 'search#overview', as: 'search_overview'

  get 'analysis_projects/:id' => 'analysis_projects#overview', as: 'analysis_project_overview'
  get 'analysis_projects/:id/timeline' => 'timelines#analysis_project', as: 'analysis_project_timeline'
  get 'analysis_projects/:id/failed_instrument_data' => 'analysis_projects#failed_instrument_data', as: 'analysis_project_failed_instrument_data'
  get 'models/:id' => 'models#status', as: 'model_status'
  get 'models' => 'models#overview', as: 'model_overview'
  get 'model_groups/coverage/:id' => 'model_groups#coverage', as: 'model_group_coverage'
  get 'model_groups/:id' => 'model_groups#overview', as: 'model_group_overview'
  get 'builds/:id' => 'builds#status', as: 'build_status'
  get 'processing_profiles/:id' => 'processing_profiles#overview', as: 'processing_profile_overview'
  get 'disks' => 'disks#overview', as: 'disk_overview'
  get 'software_results/:id' => 'software_results#overview', as: 'software_result_overview'
  get 'subjects/:id' => 'subjects#overview', as: 'subject_overview'
  get 'libraries/:id' => 'libraries#overview', as: 'library_overview'
  get '/search' => 'search#results', as: 'search_results'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  self.table_name = 'subject.subject'
  self.primary_key = 'subject_id'

  has_many :models, inverse_of: :subject
  has_many :subject_attributes, inverse_of: :subject
  has_many :libraries, foreign_key: :sample_id, inverse_of: :sample
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def overview
    @subject = Subject.where(:subject_id => params[:id]).first!
    @attributes = @subject.subject_attributes
    @models = @subject.models.page(params[:page])
    @libraries = @subject.libraries
  end
end

app/views/subjects/overview.html.haml
.row
  .container-fluid
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          = @subject.name
    .row
      .col-md-10.col-md-offset-1
        .well
          .col-md-8
            %h4 Subject Information
            %table.table.table-striped
              %thead
                %tr
                  %th Label
                  %th Value
                  %th Nomenclature
              %tbody
                - @attributes.each do |attribute|
                  %tr
                    %td= attribute.attribute_label
                    %td= attribute.attribute_value
                    %td= attribute.nomenclature
          .col-md-4
            %h4 Libraries
            %ul
              -@libraries.each do |library|
                %li= link_to library.full_name, library_overview_path(id: library.library_id)
          .clearfix
    .row
      .col-md-10.col-md-offset-1
        .col-md-12
          %h4 Models
          %ul
            - @models.each do |model|
              %li= link_to model.name, model_status_path(id: model.genome_model_id)
          = paginate @models