config/routes.rb
Rails.application.routes.draw do

  root 'search#overview', as: 'search_overview'

  get 'analysis_projects/:id' => 'analysis_projects#overview', as: 'analysis_project_overview'
  get 'analysis_projects/:id/timeline' => 'timelines#analysis_project', as: 'analysis_project_timeline'
  get 'analysis_projects/:id/failed_instrument_data' => 'analysis_projects#failed_instrument_data', as: 'analysis_project_failed_instrument_data'
  get 'models/:id' => 'models#status', as: 'model_status'
  get 'models' => 'models#overview', as: 'model_overview'
  get 'model_groups/coverage/:id' => 'model_groups#coverage', as: 'model_group_coverage'
  get 'model_groups/:id' => 'model_groups#overview', as: 'model_group_overview'
  get 'builds/:id' => 'builds#status', as: 'build_status'
  get 'processing_profiles/:id' => 'processing_profiles#overview', as: 'processing_profile_overview'
  get 'disks' => 'disks#overview', as: 'disk_overview'
  get 'software_results/:id' => 'software_results#overview', as: 'software_result_overview'
  get 'subjects/:id' => 'subjects#overview', as: 'subject_overview'
  get 'libraries/:id' => 'libraries#overview', as: 'library_overview'
  get '/search' => 'search#results', as: 'search_results'

end

app/models/analysis_project.rb
class AnalysisProject < ActiveRecord::Base
  self.table_name = 'config.analysis_project'

  has_many :config_profile_items
  has_many :analysis_project_model_bridges
  has_many :instrument_data_analysis_project_bridges
  has_many :models, through: :analysis_project_model_bridges
  has_many :instrument_data, through: :instrument_data_analysis_project_bridges
  has_many :timeline_events, foreign_key: 'object_id'
end

app/controllers/analysis_projects_controller.rb
class AnalysisProjectsController < ApplicationController
  def overview
    @analysis_project = AnalysisProject.where(id: params[:id]).first!
    inst_data_bridges = @analysis_project.instrument_data_analysis_project_bridges
      .select('status, count(instrument_data_analysis_project_bridge.id) as count')
      .group('status')

    model_ids = @analysis_project.analysis_project_model_bridges.pluck(:model_id)
    statuses = ModelStatusQuery.new(model_ids).execute
    models_by_type = @analysis_project.models.group_by(&:subclass_name)

    base_query_params = { analysis_project_id: params[:id] }

    @model_type_chart      = ModelTypeChart.new(models_by_type, base_query_params, view_context)
    @model_status_chart    = ModelStatusChart.new(statuses, base_query_params, view_context)
    @config_presenter      = AnalysisProjectConfigPresenter.new(@analysis_project)
    @instrument_data_chart = InstrumentDataChart.new(inst_data_bridges)

    @timeline              = TimelinePresenter.new @analysis_project.timeline_events
                                                     .order("updated_at DESC")
                                                     .limit(25)
    @analysis_project_disk_usage = Rails.cache.fetch("analysis project disk usage query" + params[:id]) do
     AnalysisProjectDiskUsageQuery.new.execute(params[:id]).to_a[0]['usage'].to_f/(1024*1024*1024)
    end
  end

  def failed_instrument_data
    @analysis_project = AnalysisProject.where(id: params[:id]).first!
    @failed_bridges = InstrumentDataAnalysisProjectBridge.where(status: 'failed', analysis_project: @analysis_project)
    @unique_reasons = @failed_bridges.group_by(&:reason)
  end
end

app/views/analysis_projects/failed_instrument_data.html.haml
.row
  .container-fluid
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          = link_to @analysis_project.name, analysis_project_overview_path(@analysis_project)
          %small failed instrument data
    .row
      .col-md-10.col-md-offset-1
        %h3 Unique Failure Reasons
        %ul
          - @unique_reasons.each do |(reason, items)|
            %li= "#{reason} (#{items.count})"
    .row
      .col-md-10.col-md-offset-1
        %h3 All Failed Instrument Data
        %ul
          - @failed_bridges.each do |bridge|
            %li= "#{bridge.instrument_data_id} (#{bridge.reason})"

app/views/analysis_projects/overview.html.haml
.row
  .container-fluid
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          = @analysis_project.name
    .row
      .col-md-10.col-md-offset-1
        %h4
          Analysis Project Information
          -if @analysis_project.is_cle
            .pull-right
              %span.label.label-warning
                CLE
        .well
          .col-md-6
            %dl.dl-horizontal
              %dt ID:
              %dd= @analysis_project.id
              %dt Status:
              %dd= @analysis_project.status
              %br
              %dt Instrument Data:
              %dd= @instrument_data_chart.total_items
              %br
              %dt Models:
              %dd= @model_status_chart.total_items
              %br
              %dt Disk Usage (Tb):
              %dd= number_with_precision(@analysis_project_disk_usage,precision: 2)
          .col-md-6
            %dl.dl-horizontal
              %dt Expected Model Types:
              %dd
                %ul.list-unstyled
                  -@config_presenter.expected_models.each do |model_type|
                    %li=model_type
          .clearfix
    .row
      .col-md-10.col-md-offset-1
        .col-md-4
          %h4 Instrument Data
          .well
            = render partial: 'shared/doughnut_chart', locals: { chart: @instrument_data_chart }
            = link_to 'Failed Instrument Data', analysis_project_failed_instrument_data_path(@analysis_project)
        .col-md-4
          %h4 Models By Type
          .well
            = render partial: 'shared/doughnut_chart', locals: { chart: @model_type_chart }
        .col-md-4
          %h4 Models By Status
          .well
            = render partial: 'shared/doughnut_chart', locals: { chart: @model_status_chart }
    .row
      .col-md-10.col-md-offset-1
        %h4 Project Configuration
        = render partial: 'shared/config_files', locals: {config_files: @config_presenter.config_files_markup }
    .row
      %br
    .row
      .col-md-10.col-md-offset-1
        %h4
          Timeline Events
          %small
            %a{href: analysis_project_timeline_path(@analysis_project)} View all
        = render partial: 'shared/timeline', locals: { timeline: @timeline }